### ISSUE TITLE
Broken since last Meross API update

### ISSUE THREAD

**Issue by lekr74** [colthreepv/meross-ingestor#9]
Hello,

I've just discovered that the docker container stopped working, I suppose since the last update from Meross API.
I've seen that the librairies were updated, but I don't know how to update it inside the docker container.

Here's the log : 

```
Possibly Unhandled Rejection at: Promise  Promise {

  <rejected> Error: apiStatus: 0: 

      at MerossCloud.authenticatedPost (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:62:19)

      at processTicksAndRejections (internal/process/task_queues.js:93:5)

      at async MerossCloud.connect (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:86:31)

      at async main (/usr/src/app/index.js:17:22)
```

Do you plan to update it so it can work again ?

Thanks in advance !

**Comment by stefanwendelmann** [comment]
@lekr74 same here
Build it on my RaspberryPi and then run it and got :

```
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> Error: apiStatus: 0: 
      at MerossCloud.authenticatedPost (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:62:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MerossCloud.connect (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:86:31)
      at async main (/usr/src/app/index.js:17:22)
}  reason:  Error: apiStatus: 0: 
    at MerossCloud.authenticatedPost (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MerossCloud.connect (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:86:31)
    at async main (/usr/src/app/index.js:17:22)
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> Error: apiStatus: 0: 
      at MerossCloud.authenticatedPost (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:62:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MerossCloud.connect (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:86:31)
      at async main (/usr/src/app/index.js:17:22)
}  reason:  Error: apiStatus: 0: 
    at MerossCloud.authenticatedPost (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MerossCloud.connect (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:86:31)
    at async main (/usr/src/app/index.js:17:22)
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> Error: apiStatus: 0: 
      at MerossCloud.authenticatedPost (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:62:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MerossCloud.connect (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:86:31)
      at async main (/usr/src/app/index.js:17:22)
}  reason:  Error: apiStatus: 0: 
    at MerossCloud.authenticatedPost (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MerossCloud.connect (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:86:31)
    at async main (/usr/src/app/index.js:17:22)
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> Error: apiStatus: 0: 
      at MerossCloud.authenticatedPost (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:62:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MerossCloud.connect (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:86:31)
      at async main (/usr/src/app/index.js:17:22)
}  reason:  Error: apiStatus: 0: 
    at MerossCloud.authenticatedPost (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MerossCloud.connect (/usr/src/app/node_modules/meross-cloud-ts/dist/cloud.js:86:31)
    at async main (/usr/src/app/index.js:17:22)
```
